//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class DmkDatabaseEntities : DbContext
{
    public DmkDatabaseEntities()
        : base("name=DmkDatabaseEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<AdminDetails> AdminDetails { get; set; }
    public virtual DbSet<Events> Events { get; set; }
    public virtual DbSet<portfolio> portfolio { get; set; }
    public virtual DbSet<userInfo> userInfo { get; set; }
    public virtual DbSet<videos> videos { get; set; }

    public virtual ObjectResult<Login_Check_Sp_Result> Login_Check_Sp(string email)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Login_Check_Sp_Result>("Login_Check_Sp", emailParameter);
    }

    public virtual ObjectResult<userID_Check_Sp_Result> userID_Check_Sp(string email, string fname)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var fnameParameter = fname != null ?
            new ObjectParameter("fname", fname) :
            new ObjectParameter("fname", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userID_Check_Sp_Result>("userID_Check_Sp", emailParameter, fnameParameter);
    }

    public virtual ObjectResult<userID_Check_Result> userID_Check(Nullable<int> uid)
    {
        var uidParameter = uid.HasValue ?
            new ObjectParameter("uid", uid) :
            new ObjectParameter("uid", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userID_Check_Result>("userID_Check", uidParameter);
    }

    public virtual ObjectResult<Login_Admin_Sp_Result> Login_Admin_Sp(string email)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Login_Admin_Sp_Result>("Login_Admin_Sp", emailParameter);
    }
}
